#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

MAIN_FILE="wacc/WACC"
COMPILE_FILE=$1

java -cp bin:lib/antlr-4.4-complete.jar ${MAIN_FILE} ${COMPILE_FILE} < ${COMPILE_FILE}
exit $?
