#!/usr/bin/ruby
#A script to test all valid files in the wacc examples dir

def applyANTLR(dir)
    puts "Testing valid files..."
    Dir.foreach(dir) do | file |
        if File.file?(file)
            puts "#{File.basename(file)}: "
            `java -cp bin:lib/antlr-4.4-complete.jar "WACCTest" < #{file}`
        elsif
            applyANTLR(file)
        end
    end
    puts "...finished testing"
end

validWD=`~/git/secondYear/wacc_examples/valid`
applyANTLR(validWD)

